ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.gas-spike-trap]
address = "0x98bc34449C07bE4A290D3703D672867512aD20B7"
path = "out/GasSpikeTrap.sol/GasSpikeTrap.json"
response_contract = "0x1c7065eEe97182801e1C5653eFf75d4F2034A0C8"
response_function = "handleGasSpikeAlert(uint256,uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xFC78272da0FE35AE21F4d4fa376829826adD2B79"]
